name: Run Python tests

on:
  workflow_call:
    inputs:
      package:
        description: api | ui
        required: true
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Run ruff linter
        run: ruff check ./main/${{ inputs.package }}

  run-tests:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: TeamCity Setup
        uses: ./.github/actions/teamcity-setup

      - name: Upload failure screenshot
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: teamcity-fail-screenshot
          path: teamcity_fail.png

      - name: Set test path env var
        run: |
          if [ "${{ inputs.package }}" = "api" ]; then
            echo "TEST_PATH=tests/api_tests" >> $GITHUB_ENV
          elif [ "${{ inputs.package }}" = "ui" ]; then
            echo "TEST_PATH=tests/ui_tests" >> $GITHUB_ENV

      - name: Run pytest
        continue-on-error: true
        run: PYTHONPATH=. pytest -m regression $TEST_PATH
