name: TeamCity deployment

on: push

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Allow artifact usage
        uses: actions/upload-artifact@v4
        with:
          name: dummy
          path: README.md
        continue-on-error: true
  # Собирается бекенд и деплоится на стейдж/review app
  backend:
    uses: ./.github/workflows/backend-stage.yml

  # Собирается бекенд и деплоится на стейдж/review app
  frontend:
    uses: ./.github/workflows/frontend-stage.yml

  # Прогоняются API тесты
  automation-api:
    needs: [ backend, frontend ]
    uses: ./.github/workflows/automation.yml
    with:
      package: api

  # Прогоняются UI тесты
  automation-ui:
    needs: [ backend, frontend ]
    uses: ./.github/workflows/automation.yml
    with:
      package: ui

  manual-prod-approval:
    needs: [ automation-api, automation-ui ]
    runs-on: ubuntu-latest
    environment: 'prod'
    steps:
      - name: Approve backend and frontend to production
        run: echo Approved to production

  deploy-prod:
    needs: [ manual-prod-approval ]
    uses: ./.github/workflows/backend-stage.yml